### ISSUE TITLE
Does it run on hosted CI e.g. CircleCI, TravisCI?

### ISSUE THREAD

**Issue by teohm** [twalpole/apparition#10] opened 2019-04-17 06:48 UTC
Hi, can anyone confirm if this new driver runs properly on hosted CI such as CircleCI, TravisCI etc?

I'm just started to test it on CircleCI, my RSpec test suite just hang and timed out.

```
RSpec is shutting down and will print the summary report... Interrupt again to force quit.
Too long with no output (exceeded 10m0s)
```

**Comment by twalpole** [comment] 2019-04-17 14:55
@teohm This is still in beta so it hasn't been fully tested on different CI setups however there is nothing specifically know that should stop it from working.  If you can provide a way to reproduce your issue I'll be happy to look into it.

**Comment by baffers** [comment] 2019-04-22 17:22
I'm experiencing this too with CircleCI

**Comment by twalpole** [comment] 2019-04-22 18:23
@baffers As mentioned in my previous answer -- if someone can provide a simple project that reproduces this behavior I'll be more than happy to take a look and figure out what's going wrong.

**Comment by baffers** [comment] 2019-04-22 18:38
I totally understand, as soon as I wrote that comment I was like "they're going to want an example".  it's kind of a weird week for me so if @teohm can't provide an example this week, I'll try to get one together next week

**Comment by twalpole** [comment] 2019-04-22 22:33
@baffers Sounds good -- one quick question, are you using the released gem or the master branch?

**Comment by baffers** [comment] 2019-04-22 22:43
@twalpole master. Also, once I passed in `headless: false`  into the driver config my tests started running so I'm guessing there isn't a huge problem with Apparition, just my set up. I'm hitting some  little bugs with other random things (eg, `send_keys(:return)` blows up but `send_keys(:enter)` works) but nothing that I can't work around.

**Comment by twalpole** [comment] 2019-04-23 00:01
@baffers Yeah - Looks like there's not currently a key definition for :return - so that would explain that.  Please add issues for any other things you come across that don't behave correctly , and I'll get them fixed if possible.

**Comment by twalpole** [comment] 2019-04-23 00:08
FYI - there is :enter and :numpad_enter as two different options

**Comment by skyeagle** [comment] 2019-04-25 03:07
@teohm I had the same issue, it turns out these two options helped:
```ruby
        browser_options: {
          'no-sandbox' => nil,
          'disable-features' => 'VizDisplayCompositor'
        },
```

the latter one found [here](https://github.com/GoogleChrome/puppeteer/issues/3774)

**Comment by twalpole** [comment] 2019-04-25 17:14
@skyeagle Thanks for that -- note you should also be able to pass that as

    browser_options: [ :no_sandbox, disable_features: 'VizDisplayCompositor']

to reduce the need for all the nils

**Comment by twalpole** [comment] 2019-04-25 17:15
If anyone else can confirm whether or not those two options fix the issue for them, I'll go ahead and close this

**Comment by baffers** [comment] 2019-04-25 18:04
@twalpole yes it did!

**Comment by twalpole** [comment] 2019-04-25 20:15
Great! - Closing this then.

**Closed by twalpole** 2019-04-25 20:15 UTC

**Comment by etagwerker** [comment] 2019-09-09 13:25
@twalpole Just ran into this issue and the attempts listed above did not work for me. 😢 

Here are the things I tried: 

```
require 'capybara/apparition'

Capybara.register_driver :apparition do |app|
  Capybara::Apparition::Driver.new(
    app,
    browser_options: {
      'no-sandbox' => nil,
      'disable-features' => 'VizDisplayCompositor'
    }
  )
end

Capybara.javascript_driver = :apparition
```

That didn't work. 

Then I tried: 

```
require 'capybara/apparition'

Capybara.register_driver :apparition do |app|
   Capybara::Apparition::Driver.new(app, browser_options: [ :no_sandbox, disable_features: 'VizDisplayCompositor'])
end

Capybara.javascript_driver = :apparition
```

I get a timeout from Circle CI with this output:

```
bundle exec rspec --format progress $TEST_FILES
Requested historical based timing, but they are not present.  Falling back to name based sorting
................................................Capybara starting Puma...
* Version 3.12.1 , codename: Llamas in Pajamas
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:43099
```

Is there something I'm doing wrong? 

I tried with both apparition v0.4.0 and apparition from `master`

**Comment by baffers** [comment] 2019-09-09 14:53
Hey @etagwerker I'm sure if this will help but this is our config:
```
Capybara::Apparition::Driver.new(app, {
                                         browser_logger: nil,
                                         headless: true, # TO RUN A BROWSER, CHANGE TO FALSE
                                         browser_options: [ :disable_gpu, :no_sandbox, disable_features: 'VizDisplayCompositor']
                                      }
                                 )  
```

**Comment by kjakub** [comment] 2019-10-01 16:27
i was running to the same issue on gitlab/cicd and confirming here that options from @baffers helped. @twalpole I would add link to this issue from main [README.md](https://github.com/twalpole/apparition/blob/master/README.md) , it took me some time to come here

**Comment by kjakub** [comment] 2019-10-01 16:31
@twalpole :1st_place_medal: for this repo
