### ISSUE TITLE
Chrome Version 85 fails to load resources

### ISSUE THREAD

**Issue by skyeagle** [twalpole/apparition#64] opened 2020-08-28 12:44 UTC
hi @twalpole,

thank you for amazing work on this gem!

We hit an interesting issue with the latest chrome version 85 and the driver...

The browser starts and successfully makes the first request. Right after that, all subsequent requests fail with `net::ERR_INVALID_ARGUMENT` and no other clue to what's happening. It only happens on the first page loading and if you reload the page everything seems to be working. 

There is our configuration:
```ruby
      Capybara::Apparition::Driver.new(app,
        browser_options: {
          'no-sandbox' => nil,
          'disable-web-security' => nil,
          'disable-features' => 'VizDisplayCompositor'
        },
        headless: headless,
        js_errors: false,
        window_size: [1440, 900]
      )
```

Things we have already tried:

- update apparition gem (doesn't help)
- chrome versions prior 85 (does work)
- use a different driver https://github.com/rubycdp/cuprite (also works)

In the meantime, we would like to stay with the apparition driver but this issue bothers us a lot b/c it prevents us to run any feature tests.

Any help would be really appreciated!
Thank you again for the amazing contribution and commitment to this gem!

**Comment by Ecco** [comment] 2020-08-28 13:14
Hit by the very same problem. I don't think we're using any special configuration. The problem also happen in non-headless mode.

**Comment by diachini** [comment] 2020-08-28 13:50
Also affected by this one.  If anyone else is struggling with CircleCI as a result, our temporary bandage:
```diff
-  ruby_image: &ruby_image circleci/ruby:2.7.1-node-browsers
+  ruby_image: &ruby_image circleci/ruby@sha256:919028ba2abddd4a00228549bfc3d4bc9a0a19d48bb9246be5a8503a4afa9416
```

Using the specific hash of our last passing build before the Chrome/ChromeDriver was bumped to version  85.0.4183.83

**Comment by geoffharcourt** [comment] 2020-08-28 20:33
I don't think this is an Apparition problem (it happens with Cuprite and other drivers on Chrome 85), but I haven't been able to make heads or tails of how to fix it. I tried using `add_headers` to override the `Referrer Policy` header to undo the Chrome 85 change, but wasn't able to make things work.

I don't yet understand why later requests work, but I suspect it has something to do with prefetching and caching bad responses.

**Comment by jordanfbrown** [comment] 2020-08-28 21:13
Interesting, we actually were able to successfully use Cuprite on Chrome 85. Unfortunately, switching to Cuprite broke around 200 tests in our suite so going through each one would be quite tedious.

We came up with a hack to get around the problem for now that just overrides Capybara's `visit` method to refresh the page immediately after loading it for the first time:

```ruby
RSpec::Rails::FeatureExampleGroup.class_eval do
  alias_method :old_visit, :visit
  define_method(:visit) do |*args|
    old_visit(*args)
    page.driver.refresh
  end
end
```

**Comment by geoffharcourt** [comment] 2020-08-31 20:38
Update: I had something wrong in my configuration, and confirmed this doesn't happen with Cuprite. Some other instances of the `net::ERR_INVALID_ARGUMENT` error appear to be related to tampering with headers. I'm still not able to make this work with Apparition and Chrome 85. Currently looking into whether it's possible to override the `Referrer-Policy` or to disable the check for header tampering if that's what's going on.

**Comment by geoffharcourt** [comment] 2020-09-01 00:08
Further update: somewhat unexpectedly, removing our `url_whitelist` from our Apparition settings makes everything work correctly. The `net::ERR_INVALID_ARGUMENT` error is raised when a header is unexpectedly added to a request. I went looking for places where Apparition alters headers, and `Page#process_intercepted_fetch` has a section where the setting of `url_blacklist` or `url_whitelist` has some effect on headers.

As this setting isn't present in @skyeagle's initial report, I'm not sure if there's something else going on in that report.

**Comment by evgeniradev** [comment] 2020-09-01 15:35
Not sure if this will fix your issue, but maybe try adding the below to browser_options:

'enable-features' => 'NetworkService,NetworkServiceInProcess'

**Comment by skyeagle** [comment] 2020-09-01 17:27
Thanks to all but none of the suggested solutions worked so far. 

In the meantime, we use a following dirty hack to run specs locally and an older version of Chrome on CI:

```ruby
RSpec::Rails::FeatureExampleGroup.class_eval do
  alias_method :old_visit, :visit
  define_method(:visit) do |*args|
    old_visit(*args)
    page.driver.refresh unless ENV['CIRCLECI']
  end
end
```

**Comment by evgeniradev** [comment] 2020-09-02 15:08
Hi all,

This is just to share the workarounds we are using until this gets fixed in case it helps anyone else.

1. Depending on what OS you are using, you can download either the 'chrome-mac.zip' or 'chrome-linux.zip' file from the following links and extract it(these are official older versions of the Chromium browser):
macOS: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/737173/
Linux: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Linux_x64/737173/

2. Insert the absolute path to the binary in the BROWSER_PATH env variable below to run the tests.
For example:
  macOS, BROWSER_PATH="*ABSOLUTE_PATH*/chrome-mac/Chromium.app/Contents/MacOS/Chromium"
  Linux, BROWSER_PATH="*ABSOLUTE_PATH*/chrome-mac/chrome"

The full command:
`BROWSER_PATH="" RAILS_ENV='test' bundle exec rspec`

I hope that makes senbse.

------

For **Docker**, we are using the following lines in the Dockerfile to downgrade to an earlier version of Chrome that works:

```
RUN wget http://dl.google.com/linux/deb/pool/main/g/google-chrome-unstable/google-chrome-unstable_81.0.4044.17-1_amd64.deb
RUN apt-get install -f -y ./google-chrome-unstable_81.0.4044.17-1_amd64.deb
```

**Comment by twalpole** [comment] 2020-09-02 17:19
Is everyone seeing this using the master branch of apparition?

**Comment by geoffharcourt** [comment] 2020-09-02 17:24
@twalpole using 0.6.0, the only commits since then have been docs only.

**Comment by Ecco** [comment] 2020-09-03 01:42
I initially reported using 0.5.0, but updating to 0.6.0 yields the exact same problem.

**Comment by BooVeMan** [comment] 2020-09-08 18:37
For minitest I use this in our test_helper:
```
class Capybara::Apparition::Driver
  alias_method :old_visit, :visit
  def visit(url)
    old_visit(url)
    @browser.refresh
  end
end
```

**Comment by PragTob** [comment] 2020-09-21 18:01
:wave: 

I don't have a test machine ready, but the issue might have been resolved by a new Chrome version. At least the tests seem to be passing reliably again on simplecov's CI so either the CI image we use rolled something back or this was fixed in a newer version of chrome. I'd encourage people to try this out :)

**Comment by geoffharcourt** [comment] 2020-09-21 18:05
@PragTob this appears to be the case for us now as well! Thanks for reporting!

**Comment by jordanfbrown** [comment] 2020-10-13 21:49
Following up here -- the issue is resolved for us as well with the latest Chrome version.

**Closed** 2020-10-15 19:26 UTC
